
name: Android APK Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  gradle-build:
    name: Build Android APK
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK command-line tools and platforms (CI)
        run: |
          sudo apt-get update && sudo apt-get install -y unzip wget
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O /tmp/cmdline.zip
          unzip -q /tmp/cmdline.zip -d $HOME/android-sdk/cmdline-tools
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/ || true
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses || true
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-33" "build-tools;33.0.2"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
          ls -la $ANDROID_SDK_ROOT
        env:
          ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk

      - name: Install Node.js dependencies (for Capacitor Android)
        run: npm ci

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build web app (Vite)
        run: npm run build

      - name: Copy web assets to Android (Capacitor)
        run: npx cap sync android

      - name: Build Release APK (assembleRelease)
        run: |
          set -eux
          cd android
          chmod +x ./gradlew || true
          echo "Using java: $(java -version 2>&1 | head -n 1)"
          echo "Gradle wrapper:" && ls -la ./gradlew
          ./gradlew assembleRelease --no-daemon --stacktrace

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: android/app/build/outputs/apk/release/*.apk
          retention-days: 30

  test-apk:
    name: Test APK in Emulator
    runs-on: ubuntu-latest
    needs: gradle-build
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release-apk
          path: ./apk

      - name: Start Android emulator and test APK
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel
          script: |
            adb install -r ./apk/app-release.apk
            adb shell am start -n com.your.package/.MainActivity
            # Optionally run instrumentation tests here

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: gradle-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: gradle-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

      - name: Upload unit test logs
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-logs
          path: |
            test-results || true
          retention-days: 7

  release:
    needs: [gradle-build, test-apk, lint, unit-tests]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release-apk
          path: ./apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./apk/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
